# Generated by Django 5.0.7 on 2024-08-14 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0008_delete_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.company')),
            ],
            options={
                'verbose_name_plural': 'Обьявлении',
            },
        ),
    ]
