# Generated by Django 5.0.7 on 2024-08-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_banner_options_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('schebuled', 'Заплонирован'), ('publish', 'Публичный'), ('inactive', 'нефктивный')], default='inactive', max_length=20),
        ),
    ]
