# Generated by Django 5.0.7 on 2024-08-13 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.company'),
        ),
    ]
