# Generated by Django 5.0.7 on 2024-08-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_advertisement_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
